version: '3.8'
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scriptro-app
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - VIRTUAL_HOST=backend.scriptro.com
      - VIRTUAL_PORT=888
    network_mode: "host"

networks:
  nginx-proxy:
    external: true
  app-network:
    name: scriptro-network
    driver: bridge
