# Generated by Django 5.0.6 on 2024-07-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_tool_pro_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
