# Generated by Django 5.0.6 on 2024-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_usage_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcategory',
            name='tools_count',
            field=models.IntegerField(default=0),
        ),
    ]
