# Generated by Django 5.0.6 on 2024-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_alter_tool_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolusage',
            name='usage_date',
        ),
        migrations.AddField(
            model_name='tool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='toolcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='toolusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
