# Generated by Django 5.0.6 on 2024-07-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.BigIntegerField(default=0)),
                ('total_signups', models.BigIntegerField(default=0)),
                ('total_users', models.BigIntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('total_categories', models.IntegerField(default=0)),
                ('total_tools', models.IntegerField(default=0)),
                ('homepage_tools', models.ManyToManyField(to='tools.tool')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
