# Generated by Django 5.0.6 on 2024-07-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='homepage_categories',
            field=models.ManyToManyField(to='tools.toolcategory'),
        ),
    ]
